var countdownGenerator = function (x) {
  return function(){
    return x--;
  }
};

var countdown = countdownGenerator(4);
console.log(countdown()); // T-minus 3...
console.log(countdown()); // T-minus 2...
console.log(countdown()); // T-minus 3...
console.log(countdown()); // T-minus 2...
